# create your Kivy layout in the kv language here
BoxLayout:
    orientation: 'horizontal'
    size_hint_x: 0.2
    Label:
        text: 'label'

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.8
        Button:
            color: 0.5, 0.2, 1, 1
            text: ''
        Button:
            color: 0.5, 0.2, 1, 1
            text: ''
        Button:
            color: 0.5, 0.2, 1, 1
            text: ''
        Label:
            text: 'last label'
